### ISSUE TITLE
Time input for mission editor was not convenient

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Missions#7]
in mission editor, when put down decimal e.g. 1.5 it does not accept the [point] in 1[point]5
when input frame it add .99 and change the frame

work around input full number then add [point] or input [point] first then add number or use non decimal number

**Comment by KingRaptor** [comment]
Fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/534fce9b8be630dc80d05f9e62d9207a741f5636 and published.
Thanks!
