### ISSUE TITLE
mission_runner.lua iterates with table keys in synced code

### ISSUE THREAD

**Issue by silentwings** [ZeroK-RTS/Zero-K-Missions#9]
[f=-000001] Warning: Iterating a table with keys of type "table" in synced context!
stack traceback:
    [C]: in function '(for generator)'
    [string "LuaRules/Gadgets/mission_runner.lua"]:360: in main chunk
    [C]: in function 'pcall'
    [string "LuaRules/gadgets.lua"]:213: in function 'LoadGadget'
    [string "LuaRules/gadgets.lua"]:160: in function 'Initialize'
    [string "LuaRules/gadgets.lua"]:1957: in main chunk
    [C]: in function 'Include'
    [string "LuaRules/main.lua"]:11: in main chunk 

Apologies is this is the wrong issue tracker for it - I couldn't see a repo for the mission editor itself.

**Comment by KingRaptor** [comment]
Are you planning on an MP mission? Table keys cause desyncs which is irrelevant to single player (and it didn't seem to cause issues even when MP missions were in use), so I'm not really placing a priority on this at present. But I could look at it eventually.

**Comment by Licho1** [comment]
Originally we had MP missions but i think its low priority atm (after steam)

**Comment by silentwings** [comment]
I'm not planning a MP mission - but it may still cause desyncs if a player tried to watch a replay of a mssion.

**Comment by KingRaptor** [comment]
Fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/df219182496e6cf22146f858716879cca328d60d
